package entity;

// Generated 26 ��.�. 2556, 9:47:36 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProLang generated by hbm2java
 */
@Entity
@Table(name = "pro_lang", catalog = "testhibernate")
public class ProLang implements java.io.Serializable {

	private Integer id;
	private String name;
	private String founder;
	private String year;

	public ProLang() {
	}

	public ProLang(String name, String founder, String year) {
		this.name = name;
		this.founder = founder;
		this.year = year;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "founder", nullable = false, length = 45)
	public String getFounder() {
		return this.founder;
	}

	public void setFounder(String founder) {
		this.founder = founder;
	}

	@Column(name = "year", nullable = false, length = 45)
	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

}
